apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
        - name: auth-api
          image: lokitheshady/stat-tracker-auth-api:latest
          ports:
            - containerPort: 5300
---
apiVersion: v1
kind: Service
metadata:
  name: stat-tracker-auth-api-service
spec:
  selector:
    app: stat-tracker-auth-api
  ports:
    - protocol: TCP
      port: 5300
      targetPort: 5300
  type: LoadBalancer
